insert into user_settings (mode, calling_start, calling_end, timezone, data_retention_days, require_human_approval)
values ('mock', '10:00', '18:00', 'Asia/Singapore', 30, true);

insert into prospects (
  slug,
  name,
  category,
  location,
  address,
  phone,
  rating,
  review_count,
  website_status,
  social_presence,
  opportunity_score,
  estimated_deal_value,
  status,
  agent_state,
  summary,
  why_good_prospect,
  online_booking_value,
  public_info,
  inferred_info
) values
(
  'orchard-bloom-salon',
  'Orchard Bloom Salon',
  'Salon',
  'Orchard',
  'Mock address near Orchard Road, Singapore',
  '+65 6000 0101',
  4.7,
  84,
  'no_website',
  array['Instagram'],
  91,
  399,
  'Discovered',
  'DISCOVERING',
  'Independent salon with strong review signals and no detected website.',
  'High rating, many public reviews and a service category where appointment requests are valuable.',
  'Appointments and stylist availability can be captured through a simple booking CTA.',
  array['Mock public listing data only.'],
  array['Likely loses search traffic to nearby salons with booking pages.']
),
(
  'river-valley-tutors',
  'River Valley Tutors',
  'Tuition centre',
  'River Valley',
  'Mock address near River Valley Road, Singapore',
  '+65 6000 0202',
  4.6,
  63,
  'weak_website',
  array['Facebook'],
  82,
  499,
  'Discovered',
  'DISCOVERING',
  'Neighbourhood tuition centre with strong parent reviews but weak digital presence.',
  'Parents compare tuition centres online before enquiring.',
  'Trial-class booking and level-based enquiry forms can improve conversion.',
  array['Mock public listing data only.'],
  array['Parents likely need details by subject and level before enquiring.']
);
