"use client";

import type { GeneratedWebsite, Prospect } from "@/lib/types";
import { cn } from "@/lib/utils";

const styleMap = {
  emerald: {
    bg: "bg-[#f8fffb]",
    accent: "text-emerald-700",
    button: "bg-emerald-600 text-white",
  },
  indigo: {
    bg: "bg-[#f8f9ff]",
    accent: "text-indigo-700",
    button: "bg-indigo-600 text-white",
  },
  amber: {
    bg: "bg-[#fffaf1]",
    accent: "text-amber-700",
    button: "bg-amber-600 text-white",
  },
};

export function GeneratedSitePreview({
  website,
  prospect,
  compact = false,
}: {
  website: GeneratedWebsite;
  prospect: Prospect;
  compact?: boolean;
}) {
  const styles = styleMap[website.theme.style];
  const hero = website.sections.find((section) => section.kind === "hero");
  const sections = website.sections.filter((section) => section.kind !== "hero");

  return (
    <div
      className={cn(
        "overflow-hidden rounded-lg border border-zinc-200 bg-white text-zinc-950 shadow-2xl shadow-black/20",
        compact ? "text-[11px]" : "text-sm",
      )}
    >
      <header className="flex items-center justify-between border-b border-zinc-200 px-5 py-4">
        <div className="font-bold">{prospect.name}</div>
        <nav className="hidden gap-4 text-xs text-zinc-500 sm:flex">
          <span>Services</span>
          <span>Reviews</span>
          <span>Location</span>
        </nav>
      </header>
      <section className={cn("px-5 py-8", styles.bg)}>
        <p className={cn("text-xs font-semibold uppercase", styles.accent)}>
          {prospect.category} · {prospect.location}
        </p>
        <h1 className="mt-3 max-w-2xl text-3xl font-bold tracking-normal">
          {hero?.title}
        </h1>
        <p className="mt-3 max-w-2xl leading-6 text-zinc-600">{hero?.body}</p>
        <button className={cn("mt-5 rounded-lg px-4 py-2 text-sm font-semibold", styles.button)}>
          Enquire now
        </button>
      </section>
      <main className="grid gap-4 px-5 py-5 sm:grid-cols-2">
        {sections.map((section) => (
          <section key={section.id} className="rounded-lg border border-zinc-200 p-4">
            <h2 className="font-semibold">{section.title}</h2>
            <p className="mt-2 leading-6 text-zinc-600">{section.body}</p>
          </section>
        ))}
      </main>
      <footer className="border-t border-zinc-200 px-5 py-4 text-xs text-zinc-500">
        Preview generated by RevenueLoop. Owner approval required before publication.
      </footer>
    </div>
  );
}
